# https://docs.awesomeapi.com.br/api-de-moedas
@moedas=USD-BRL,EUR-BRL,BTC-BRL
get https://economia.awesomeapi.com.br/json/last/{{moedas}}
Accept: application/json
###

get http://localhost:8080/cotacao
Accept: application/json