version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - STORAGE_REDIS_URL=redis://redis:6379/0
      - SERVER_PORT=8080
      - STORAGE_TYPE=redis
